env:
  browser: true
  commonjs: true
  jquery: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-unexpected-multiline": "off",
}
globals:
  L: readonly  # Defined by Leaflet.
  pane: writable  # Defined by Leaflet.
