env:
  browser: true
  commonjs: true
  jquery: true
extends:
  - eslint:recommended
  - airbnb-base
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unexpected-multiline: off
  no-use-before-define: off
globals:
  L: readonly  # Defined by Leaflet.
  pane: writable  # Defined by Leaflet.
