extends:
  - eslint:recommended
  - airbnb-base
  - prettier
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unexpected-multiline: off
  import/no-unresolved: off
  import/extensions: off
  "@typescript-eslint/no-unused-vars": off
