name: Deploy to staging
on:
  push:
    branches: [main]
jobs:
  deploy_staging:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Serve dist/ folder
        run: |
          npm run serve-dist &
          sleep 10 # give server some time to start
      - name: Run tests on dist/
        run: npm run test-dist
      - name: Archive dist/ contents
        run: |
          cd dist
          tar -czf ../dist_contents.tar.gz *
      - name: Copy dist/ to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: dist_contents.tar.gz
          target: /var/www/${{ secrets.SERVER_HOST }}/plm-staging
      - name: Extract on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            tar -xzf /var/www/${{ secrets.SERVER_HOST }}/plm-staging/dist_contents.tar.gz -C /var/www/${{ secrets.SERVER_HOST }}/plm-staging
            rm /var/www/${{ secrets.SERVER_HOST }}/plm-staging/dist_contents.tar.gz
