name: Deploy site
on:
  push:
    branches: [main]
jobs:
  deploy:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Serve dist/ folder
        run: |
          npm run serve-dist &
          sleep 8 # give server some time to start
      - name: Run tests on dist/
        run: npm run test-dist
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: dist/*
          target: /var/www/parkingreform.org/plm-staging
