name: Tests
on: [push, pull_request]
jobs:
  build:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Start server
      run: |
        npm start &
        sleep 3 # give server some time to start
    - name: Run tests
      run: npm test
